---
name: BuildReleaseContainerImage

on:
  push:
    tags:
      - 'v*'

env:
  REPO: frezes
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push docker images
        if: github.event_name == 'push'
        run: |
          tag=$(cat VERSION | tr -d " \t\n\r")
          docker buildx build --build-arg="VERSION=${tag}"  --platform linux/amd64,linux/arm64 --push -t ${REPO}/cortex-tenant:${tag} -f Dockerfile.multiarch .